# yazi.toml
[mgr]
show_hidden = true
scrolloff = 4

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = 'hx "$@"', block = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', orphan = true, desc = "Open" },
]

[open]
prepend_rules = [
	# open with normal
	{ name = "*.ods", use = "open" },
	{ name = "*.pdf", use = "open" },
	
	# open with multimedia player
	{ name = "*.mp3", use = "play" },

]
append_rules = [
	{ name = "*", use = "edit" },
]

