"$schema" = "https://starship.rs/config-schema.json"

# Set new line
add_newline = false

# Set the default palette
palette = "catppuccin_mocha"

# Left side
format = """$directory$git_branch$character"""

# Right side
# right_format = """$cmd_duration$status"""

# Set line break
[line_break]
disabled = true

# Configure the directory
[directory]
style = "blue"
format = "[$path]($style) "
truncation_length = 4
truncation_symbol = "…/"

# Git branch
[git_branch]
style = "mauve"
format = "on [$branch]($style) "
only_attached = false

# Status for errors
[status]
format = " [$status]($style)"
style = "red"
disabled = false

# Command duration
[cmd_duration]
format = "took [$duration]($style)"

# Prompt character
[character]
success_symbol = "[∙](green)"
error_symbol = "[∙](red)"
format = "$symbol "

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
