theme = "catppuccin_mocha_custom"

[editor]
mouse = true
cursorline = true
color-modes = true
scrolloff = 10
line-number = "relative"
# end-of-line-diagnostics = "hint"

# [editor.inline-diagnostics]
# cursor-line = "warning"

[editor.gutters]
layout = ["diff", "spacer", "diagnostics", "spacer", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-indent-retain = 0

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.f]
s = ":write"
S = ":write!"
w = ":write-all"
W = ":write-all!"
q = ":buffer-close"
Q = ":buffer-close!"
x = ":buffer-close-others"
X = ":buffer-close-others!"
d = ":reset-diff-change"
r = ":reload-all"
