theme = "catppuccin_mocha_custom"

[editor]
mouse = true
scrolloff = 10
cursorline = true
color-modes = true
text-width = 80
popup-border = "all"
line-number = "relative"

[editor.gutters]
layout = ["diagnostics", "spacer", "diff", "line-numbers", "spacer", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = false

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

C-y = [
  ':sh rm -f /tmp/unique-file',
  ':insert-output yazi %{buffer_name} --chooser-file=/tmp/unique-file',
  ':insert-output echo "\x1b[?1049h\x1b[?2004h" > /dev/tty',
  ':open %sh{cat /tmp/unique-file}',
  ':redraw',
]
