theme = "catppuccin_mocha_custom"

[editor]
mouse = true
cursorline = true
color-modes = true
scrolloff = 10
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.auto-save]
focus-lost = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.gutters]
layout = ["diff", "spacer", "diagnostics", "spacer", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-indent-retain = 0

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-r = [":reload-all"]
C-l = [":lsp-restart"]
C-a = [":reset-diff-change"]
C-x = [":buffer-close"]
C-q = [":buffer-close-others"]
