theme = "catppuccin_mocha_custom"

[editor]
mouse = true
cursorline = true
color-modes = true
scrolloff = 10
line-number = "relative"
# end-of-line-diagnostics = "hint"

# [editor.inline-diagnostics]
# cursor-line = "hint"

[editor.gutters]
layout = ["diff", "spacer", "diagnostics", "spacer", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true
max-indent-retain = 0

[editor.lsp]
display-color-swatches = false

[editor.whitespace.render]
space = "none"
tab = "none"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
tab = ""
nbsp = "▯"
nnbsp = "▮"
newline = ""

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.","]
s = ":write"
S = ":write!"
w = ":write-all"
W = ":write-all!"
x = ":buffer-close"
X = ":buffer-close!"
q = ":buffer-close-others"
Q = ":buffer-close-others!"
d = ":reset-diff-change"
r = ":reload-all"
