theme = "catppuccin_mocha_custom"

[editor]
mouse = true
scrolloff = 10
cursorline = true
color-modes = true
text-width = 80
popup-border = "all"
line-number = "relative"
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.gutters]
layout = ["diff", "spacer", "diagnostics", "spacer", "line-numbers", "spacer"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = false

[editor.soft-wrap]
enable = true
max-indent-retain = 0

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-r = [":reload-all"]
C-a = [":reset-diff-change"]
C-x = [":buffer-close"]
C-q = [":buffer-close-others"]
